name: fsce_net
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.8
  - pip
  - pip:
    - numpy==1.24.4
    - pandas==2.0.3
    - scipy==1.10.1
    - scikit-learn==1.3.2
    - matplotlib==3.7.5
    - seaborn==0.13.2
    - tqdm==4.67.1
    - openpyxl==3.1.5
    - transformers==4.46.3
    - pyyaml
    - pillow